### ISSUE TITLE
In compatible with current flutter_svg version

### ISSUE THREAD

**Issue by greatpie** [dnfield/lottie-flutter#24]
Because every version of lottie_flutter depends on path_drawing ^0.2.1, flutter_svg ^0.12.0 is incompatible with lottie_flutter.

**Comment by dnfield** [comment]
I took a look at this but managed to break the build for it locally.  If you can, try using a dependency_override and it should be fine - in the mean time I'm looking at alternative approaches.

**Comment by GianlucaCesari** [comment]
Any news on this? I too encountered the same problem and not knowing how dependency_override works i had to bump down flutter_svg to 0.5.0 , the problem is all my svg are now broken 😅

@dnfield can you maybe post a snippet to let us know how we can use dependency_override in this case?

**Comment by dnfield** [comment]
Something like this should work:

```yaml
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_svg: ^0.12.0
  lottie_flutter: any
  flutter:
    sdk: flutter

dependency_overrides:
  path_drawing: ^0.4.0
```
